### PR TITLE
Make IgnoringCyclicReferences working for the types overriding Equals()

### LINKED ISSUE #1370: Combination of ComparingByMember and IgnoreCyclicReferences doesn't work
### Description

If I keep it short: having override `Equals` on objects I have to disable using it with `ComparingByMembers`. But if I do so, the `IgnoreCyclicReferences` seem to stop working.

Here the details.

We have written a lot of NHibernate persistence tests, where we are using FluentAssertions `BeEquivalentOf`.
After adding a recommended for NH Equals-override in the DomainBase class we've got multiple issues with FluentAssertions.
We had to add a Configuration option `ComparingByMembers<DomainBase>()` to prevent FluentAssertions using Equals-override for comparing objects equivalence. And it worked nice for the most of cases, but has introduced another issue - now FluentAssertions seem to ignore the option `IgnoreCyclicReferences()`

### Complete minimal example reproducing the issue

Here is the minimal example I could make to reproduce the issue:

```csharp
[TestFixture]
public class FluentAssertionsIssueTest {
    public class Base {
        public Guid Id { get; set; }
        // NHibernate recommends overriding Equals for preventing issues with Sets and while working with multiple sessions, as well as issues with proxies in collections
        public override bool Equals(object obj)  {
            if (ReferenceEquals(this, obj))
                return true;
            return (obj is Base baseObj) && baseObj.Id == Id;
        }
    }

    public class Item : Base {
        public string Title { get; set; }
        public Item Previous { get; set; }
        public Item Next { get; set; }
    }

    [Test]
    public void IgnoreCyclicReferences_Broken()  {
        // imitating NHibernate save in one session
        var first = new Item() {Id = Guid.NewGuid(), Title = "First"};
        var second = new Item() {Id = Guid.NewGuid(), Title = "Second", Previous = first};
        first.Next = second;

        // imitating NHibernate load in another session
        var firstCopy = new Item() {Id = first.Id, Title = first.Title};
        var secondCopy = new Item() {Id = second.Id, Title = second.Title, Previous = firstCopy};
        firstCopy.Next = secondCopy;

        // I'd like to check, that all the properties could be persisted correctly.

        // "The maximum recursion depth was reached" is generated here (IgnoringCyclicReferences doesn't seem to work)
        firstCopy.Should().BeEquivalentTo(first, opt => opt.ComparingByMembers<Base>()
            .IgnoringCyclicReferences(), "they are equivalent");
        first.Title = "Changed";
        //  Removing Equals-override from Base class fixes FA issues, but introduces NHibernate-issues
        //  Removing ComparingByMembers-option removes "The maximum recursion depth was reached", but breaks this check (changed Title is not considered)
        firstCopy.Should().NotBeEquivalentTo(first, opt => opt.ComparingByMembers<Base>()
            .IgnoringCyclicReferences(), "after change");
    }
}
```

### Expected behavior:

Deep object comparison should be done, handling cyclic references correctly. The test should pass

### Actual behavior:

I cannot use deep object comparison on objects with overridden `Equals` and cyclic references. 
The test fails with message:
```
The maximum recursion depth was reached.  
The maximum recursion depth was reached.  
The maximum recursion depth was reached.  
The maximum recursion depth was reached.  

With configuration:
- Use declared types and members
- Compare enums by value
- Ignoring cyclic references
- Match member by name (or throw)
- Without automatic conversion.
- Be strict about the order of items in byte arrays

   bei FluentAssertions.Execution.LateBoundTestFramework.Throw(String message)
   bei FluentAssertions.Execution.CollectingAssertionStrategy.ThrowIfAny(IDictionary`2 context)
   bei FluentAssertions.Equivalency.EquivalencyValidator.AssertEquality(EquivalencyValidationContext context)
```

If I comment out `override Equals` everything works in FA, but introduces issues with NHibernate.
If I remove options `ComparingByMembers<Base>()` in both `BeEquivalentTo` / `NotBeEquivalentTo`, then the difference of Title in firstCopy and first is not detected in the `NotBeEquivalentTo`-Check.

### Versions

* 5.10.3, 5.10.2
* Using .NET framework 4.6.1

### PR DESCRIPTION
**Pull request by Serg046**
## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [x] If the contribution adds a feature or fixes a bug, please update [**the release notes**](https://github.com/fluentassertions/fluentassertions/tree/master/docs), which are published on the [website](https://fluentassertions.com/releases).
* [x] If the contribution changes the public API the changes needs to be included by running `AcceptApiChanges.ps1`/`AcceptApiChanges.sh`.
* [x] If the contribution affects [the documentation](https://github.com/fluentassertions/fluentassertions/tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

Fixes #1370

### CODE REVIEW

**Comment by Serg046** [comment]
Implemented what Compare-Net-Objects use. They use a set of ordered comparers where each the comparer has a check if the type is applicable or not. The comparer which will be in use is the first one passing the check.

 This is their [SimpleTypeComparer](https://github.com/GregFinzer/Compare-Net-Objects/blob/master/Compare-NET-Objects/TypeComparers/SimpleTypeComparer.cs) which is ordered right before ClassComparer and this is its [TypeHelper.IsSimpleType](https://github.com/GregFinzer/Compare-Net-Objects/blob/master/Compare-NET-Objects/TypeHelper.cs#L367-L384).

**Comment by Serg046** [comment]
Re-opening this to show you the idea. 3 tests are failing because `System.Type` and `UriBuilder` are not simple types anymore. So the solution could be trying to extend that hardcoded types dictionary in the change. Anyway, even if we don't try to merge something like this, we will still have the issue described by this test (fails on develop):

```csharp
[Fact]
public void Test()
{
    // Arrange
    var valueObject = new ValueObject("value");
    var valueObjectDto = new ValueObjectDto("value");

    // Act
    Action act = () => valueObject.Should().BeEquivalentTo(valueObjectDto);

    // Assert
    act.Should().NotThrow();
}

public class ValueObject
{
    public ValueObject(string value)
    {
        Value = value;
    }

    public string Value { get; }

    public override bool Equals(object obj)
    {
        return ((ValueObject)obj).Value == Value;
    }

    public override int GetHashCode()
    {
        return Value.GetHashCode();
    }
}

public class ValueObjectDto
{
    public ValueObjectDto(string value)
    {
        Value = value;
    }

    public string Value { get; }

    public override bool Equals(object obj)
    {
        return ((ValueObjectDto)obj).Value == Value;
    }

    public override int GetHashCode()
    {
        return Value.GetHashCode();
    }
}
```

**Comment by dennisdoomen** [comment]
I think you're approaching this from the wrong angle. The basic design principle FA should use is that anything that overrides `Equals` should be treated as value types. The bug that #1370 concludes with is that the cyclic reference detector is using a different algorithm.

**Comment by Serg046** [comment]
Yes but if we keep the same approach for value types we will have this issue I described above. That issue is not related to cyclic references at all and looks quite important imo. Maybe I should open a separate issue for that.
Closing the PR again as it got some attention.

**Pull request closed without merging**
