### PR TITLE
[WIP] create assertions for e.g. ReadOnlySpan

### PR DESCRIPTION
**Pull request by lg2de**
I found the issue #902 .
Here is a very simple prove of concept.
Do you think this could be implemented this way?

BTW: The changes on sln file was done automatically by Visual Studio, may be related to recent version 16.5.0.

### CODE REVIEW

**Comment by jnyrup** [comment]
Calling `ToArray` is also my best guess as the `Span` anyways would need to be converted into something that can be stored in `Subject`.

Question: 
* If we convert the `Span<T>` to an `IEnumerable<T>`, should we just return an `SelfReferencingCollectionAssertions` instead?

Note: netcore2.1 also supports these types out of the box.

Up for discussion:
* Should `ReadOnlySpan<char>` use `StringAssertions`?
* Should we add a dependency on `System.Memory` for net47 and netstandard2.0 to support these types across all targets?

**Comment by dennisdoomen** [comment]
I don't think we should not be reusing the `SelfReferencingCollection` base-class here. Looking at the [docs](https://docs.microsoft.com/en-us/dotnet/api/system.readonlyspan-1?view=netcore-3.1), it seems Microsoft already created a lot of methods to support this model. Although I'm in doubt if the performance impact is worth it.

**Comment by jnyrup** [comment]
@dennisdoomen was the double negation in your first sentence intended?

**Comment by dennisdoomen** [comment]
@lg2de any intentions to complete this PR?

**Comment by lg2de** [comment]
I do not have (anymore) a real-world use case to complete this.
So, I'll close the PR for now.

**Pull request closed without merging**
