### PR TITLE
update .net core sdk

### PR DESCRIPTION
**Pull request by jnyrup**
`<PackageIcon>` was included with [nuget 5.3.0/dotnet core 3.0.100](https://docs.microsoft.com/en-us/nuget/release-notes/nuget-5.3).
It does not specify if it is available in any preview version of .Net Core 3.0, but the feature was merged at [August 23](https://github.com/NuGet/NuGet.Client/pull/3006) in .Net Core 3.0-preview7 was released at [July 23](https://dotnet.microsoft.com/download/dotnet-core/3.0#3.0.0-preview7).
So I hope this solves #1186

### CODE REVIEW

**Comment by jnyrup** [comment]
I have no idea why the build is failing.
In desperation I tried to update Nuke as well, but it gave the same error.

I can run `build.ps1` locally.

**Comment by dennisdoomen** [comment]
I've just switch the build image on AppVeyor from _Visual Studio 2019 Preview_ to _Visual Studio 2019_, but that didn't make a difference.

**Comment by jnyrup** [comment]
Nailed it.
https://github.com/NuGet/Home/issues/8074 in nuget 5.3, i.e. .Net Core 3.0 stable
changed the syntax for downloading multiple packages using `<PackageDownload>` from
```
<PackageDownload Include="NSpec" Version="[1.0.13]" />
<PackageDownload Include="NSpec" Version="[2.0.1]" />
<PackageDownload Include="NSpec" Version="[3.1.0]" />
```

to
```
<PackageDownload Include="NSpec" Version="[1.0.13];[2.0.1];[3.1.0]" />
```

The reason it failed was that the behavior changed when using the old syntax changed from "download all three packages" to "only download the first one"
and hence 2.0.1 and 3.1.0 wasn't be downloaded.
It worked for me locally as I had the 2.0.1 and 3.1.0 in my local nuget cache.

@matkoch You might be interested in this, if you didn't already know.

**Comment by jnyrup** [comment]
And I've just confirmed, using Package Explorer, that the icon works again.

**Pull request merged**
