### PR TITLE
Use ordinal comparison in StringAssertions instead of culture-sensitive comparison

### LINKED ISSUE #1096: String .BeEquivalentTo() is case-sensitive on linux
It seems that `BeEquivalentTo()` doesn't ignore case when comparing strings on **Linux** environment.

```csharp
"SomeString".Should().BeEquivalentTo("somestring");
```

Expected: verification passes.

It works as expected on **Windows**, but throws `but "SomeString" differs near "Som" (index 0)` exception on **Linux**.

On the same environment string assertion from NUnit framework works as expected.
```csharp
StringAssert.AreEqualIgnoringCase("SomeString", "somestring");
```

Info:
- FluentAssertions v5.7.0
- .netcoreapp 2.1

### PR DESCRIPTION
**Pull request by kimsey0**
## IMPORTANT 

* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [ ] If the contribution affects the documentation, please include your changes to [**documentation.md**](https://github.com/fluentassertions/fluentassertions/blob/master/docs/_pages/documentation.md) in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com).

Fixes #1096

### CODE REVIEW

**Comment by eNeRGy164** [comment]
Shouldn't `StartWith` and `EndsWith`calls in other places be adjusted? To make sure FA is consistent on all OS/Cultures.
F.e. in the following files:

- CallerIdentifier.cs
- Execution/LateBoundTestFramework.cs
- Primitives/StringAssertions.cs
- Types/TypeSelector.cs

**Comment by jnyrup** [comment]
Agree.
We should also be explicit when using the following string methods, as not specifying a `StringComparison` [defaults](,23804789ea4c9c0e) to `StringComparison.CurrentCulture`.
* `StartsWith`
* `EndsWith`
* `IndexOf`
* `LastIndexOf`
* `Compare`

**Comment by kimsey0** [comment]
I did originally do a full search and replace from `StringComparison.CurrentCulture` to `StringComparison.Ordinal`, but since there are no existing tests for culture-sensitive behavior and I'm not sure I can figure out the potential impact of changing it in each of the places mentioned by @eNeRGy164, I ended up only committing the changes in StringAssertions.

Should I go ahead with the full search and replace plus adding `StringComparison.Ordinal` to all the calls mentioned by @jnyrup?

**Comment by jnyrup** [comment]
@kimsey0 It would be an appreciated contribution if you would do the replacements/additions and succeed in adding culture aware tests. That should finally(!) give Fluent Assertions consistent and expected behaviour.
If you need other cultures besides Danish to test against, we have earlier fixed problems due to German and Polish cultures.

**Comment by jnyrup** [comment]
@kimsey0 How are things working out? 
We're getting close to release 5.10.0, and it would be great to have this in.
Anything's blocking you or just lack of time?
Let me know if you need any help.

**Comment by kimsey0** [comment]
Just lack of time. How's your timeline on 5.10.0? When would you like to have this merged for it to ship with that release?

**Comment by jnyrup** [comment]
@kimsey0 We don't have a lot of progress from merging a PR to releasing a new version, so in practice in can be merged last minute.

I am hoping to release 5.10.0 this year.

**Comment by dennisdoomen** [comment]
Let's move this to 6.0. Hopefully @kimsey0 is willing to do the work @jnyrup requested.

**Comment by dennisdoomen** [comment]
@kimsey0 are you still up for it?

**Pull request closed without merging**
