### PR TITLE
Improve code coverage of fake should overloads

### PR DESCRIPTION
**Pull request by jnyrup**
This PR adds tests covering the fake `Should` overloads.

I first aimed for test that would find all the relevant types itself, but even before reaching that goal the test became quite unreadable.
So went with a `Theory`, which should be manageable for contributors, as `Should_methods_have_a_matching_overload_to_guard_against_chaining_and_constraints` will complain about missing `Should` overloads.

Thanks to @eNeRGy164 for the inspiration.

### CODE REVIEW

**Comment by eNeRGy164** [comment]
Totally not important, but would an expression body/lambda style method fix this line counted as not covered?
image

**Comment by jnyrup** [comment]
I should be able to just to annotate `InvalidShouldCall` with `[DoesNotReturn]`
https://github.com/coverlet-coverage/coverlet/pull/904

**Comment by eNeRGy164** [comment]
Nice!

**Review by dennisdoomen — APPROVED** [review]
Nice

**Pull request merged**
