### PR TITLE
Add missing tests for matching `null` with a wildcard

### PR DESCRIPTION
**Pull request by IT-VBFK**
This refs #1823 

## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

### CODE REVIEW

**Review by dennisdoomen — APPROVED** [review]

**Comment by IT-VBFK** [comment]
Since the tests for overridden `Equals` are covered in PR #1891 remove them here

**Comment by jnyrup** [comment]
Was this test intended to add coverage for https://coveralls.io/builds/48309149/source?filename=Src%2FFluentAssertions%2FPrimitives%2FStringWildcardMatchingValidator.cs#L54 ?
As currently it does not add any extra coverage.

In any case, I'm fine with having this test as it acts as documentation of how `Match` should be behave.

**Comment by IT-VBFK** [comment]
Hmm.. true 🤔

That was the intention of this test.. I have no idea how to set up the scenario to get into this path? 

Removing is not an option? 🫢

**Comment by jnyrup** [comment]
The null check in `CleanNewLines` can be removed as it is unreachable.
Line 33 and 35 together validates that both `Subject` and `Expected` are non-null.
https://github.com/fluentassertions/fluentassertions/blob/9e03620a904861a7c5aa66de00283a36155cc8e4/Src/FluentAssertions/Primitives/StringValidator.cs#L33-L35

**Comment by IT-VBFK** [comment]
Yeah.. that what I meant :)

Removing this as well..

**Review by jnyrup — APPROVED** [review]

**Pull request merged**
