### PR TITLE
Use 'npm' for yarn packages.

### PR DESCRIPTION
**Pull request by jnyrup**
According to [docs](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#package-ecosystem) 'npm' should also be used for yarn.

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by ITaluone** [comment]
I think the nuget step can be removed, since: 
image

**Comment by jnyrup** [comment]
> I think the nuget step can be removed, since our version is >4.8: image

Hmm... I did see that line, but wasn't sure what to get from it.
I tested this on https://github.com/jnyrup/fluentassertions/pulls and there it did open up PRs for nuget packages.

**Comment by ITaluone** [comment]
But in this repo it doen't?

Strange...

**Comment by jnyrup** [comment]
I _suspect_ that fixing yarn -> npm makes it run.
It didn't open PRs in my fork until I pushed this fix.

**Review by dennisdoomen — APPROVED** [review]

**Comment by IT-VBFK** [comment]
😆 wow.. this PR-spamming now :D

**Pull request merged**
