### PR TITLE
Prepare for .NET8 analyzers

### PR DESCRIPTION
**Pull request by jnyrup**
I installed the latest .NET8 preview to see what analyzers we would trigger.

These three lines trigger [CA1861: Avoid constant arrays as arguments](https://learn.microsoft.com/en-gb/dotnet/fundamentals/code-analysis/quality-rules/ca1861)
https://github.com/fluentassertions/fluentassertions/blob/343e80ff81a0598f58d241ba7a4f1588e3fff35d/Src/FluentAssertions/Common/MemberPath.cs#L119
https://github.com/fluentassertions/fluentassertions/blob/343e80ff81a0598f58d241ba7a4f1588e3fff35d/Src/FluentAssertions/Common/StringExtensions.cs#L121
https://github.com/fluentassertions/fluentassertions/blob/343e80ff81a0598f58d241ba7a4f1588e3fff35d/Src/FluentAssertions/Equivalency/Execution/ObjectReference.cs#L42

As I see it, we have three options here:
* Follow the analyzer and extract the constant arrays to static readonly fields. 
  * Downside: Reduced locality of the values
* Suppress CA1861 locally with `#pragma`s.
  * Downside: Added preprocessor noise.
* Suppress CA1861 for the entire project like I did for tests.
  * Downside: no warnings anywhere

I'm probably fine with either, but lean mostly towards either of the first two.

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by ITaluone** [comment]
> `.Split(new[] { '.', '[', ']' }, StringSplitOptions.RemoveEmptyEntries); `

A dump way could be: `.Split(".[]".ToCharArray(), StringSplitOptions.RemoveEmptyEntries); `

**Comment by lg2de** [comment]
> A dump way could be: `.Split(".[]".ToCharArray(), StringSplitOptions.RemoveEmptyEntries); `

This creates an array on the fly, too. This is what the rule tries to prevent, isn't it?

I recommend a field. This is not that local definition, but gives the list a name.

**Comment by dennisdoomen** [comment]
Will a local `const` variable also work?

**Review by dennisdoomen — APPROVED** [review]

**Comment by jnyrup** [comment]
> Will a local `const` variable also work?

No, it gives: `CS0133: The expression being assigned must be constant`

@dennisdoomen Can I interpret this as you vote for option 2?

**Comment by dennisdoomen** [comment]
> Can I interpret this as you vote for option 2?

I'm leaning a little bit towards 3, but I can live with 2.

**Pull request merged**
