### PR TITLE
Added `TypeEquivalencyStep` for asserting types are equal when asserting equivalency. Useful when working with polymorphic models that do not implement equality.

### PR DESCRIPTION
**Pull request by ryanholden8**
## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [x] If the contribution adds a feature or fixes a bug, please update [**the release notes**](https://github.com/fluentassertions/fluentassertions/tree/master/docs), which are published on the [website](https://fluentassertions.com/releases).
* [x] If the contribution changes the public API the changes needs to be included by running `AcceptApiChanges.ps1`/`AcceptApiChanges.sh`.
* [x] If the contribution affects [the documentation](https://github.com/fluentassertions/fluentassertions/tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

### CODE REVIEW

**Comment by dennisdoomen** [comment]
> I think we'll need something more fluent. Something like WithStrictTypeChecking. And if consistency with other APIs, we would like to have the option to specify the type using a generic overload of WithStrictTypeChecking.

Hi @ryanholden8. Are you planning to rewrite this PR to use what we suggested?

**Comment by ryanholden8** [comment]
Hi @dennisdoomen, I'd like to but I'm not sure I follow what is being requested. Sorry - it looks I forgot to response with that.

Perhaps an example of how the end code would look would help? Is this what is being requested?

 ```
return collection.BeEquivalentTo(expectation, options => config(options).WithStrictTypeChecking<T>());
```

Can you expound upon on how the generic type param would change the assertion process?

For example, if I did this: 

 ```
return collection.BeEquivalentTo(expectation, options => config(options).WithStrictTypeChecking<Order>());
```

Would that mean all other types would not have their types asserted against?

**Comment by dennisdoomen** [comment]
Just like `WithStrictOrdering` and `ComparingByMembers`:

`collection.Should().BeEquivalentTo(otherCollection, options => options.WithStrictTyping());
`collection.Should().BeEquivalentTo(otherCollection, options => options.WithoutStrictTyping());
`collection.Should().BeEquivalentTo(otherCollection, options => options.WithStrictTypingFor<Order>());
`collection.Should().BeEquivalentTo(otherCollection, options => options.WithoutStrictTypingFor<Order>());

The reason why we also need a `WithoutStrictTyping` is that you may call `WithStrictTyping` on the global `AssertionOptions`, but then want to revert that behavior for an individual assertion.

**Comment by dennisdoomen** [comment]
@ryanholden8 do you still intend to finish this?

**Comment by dennisdoomen** [comment]
Will be superseded by another PR

**Pull request closed without merging**
