### PR TITLE
Add ThatAre[Not]Abstract, ThatAre[Not]Overridable to MethodInfoSelector (as mentioned in More Assertions on types #645)

### PR DESCRIPTION
**Pull request by 94sedighi**
…or (as mentioned in More Assertions on types #645)

## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [x] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

### CODE REVIEW

**Comment by jnyrup** [comment]
See https://github.com/fluentassertions/fluentassertions/pull/2052#issuecomment-1335217321

I also [asked you](https://github.com/fluentassertions/fluentassertions/issues/645#issuecomment-1333811476) to open an issue about `BeOverridable` for API approval before implementing it.

**Comment by 94sedighi** [comment]
Well I thought this was for PropertyInfoSelector

**Comment by 94sedighi** [comment]
I will remove ´ThatAre[Not]Overridable´ and make a new PR.

**Comment by jnyrup** [comment]
I'm sorry if I was unclear, but is why we'd like to explicitly approve APIs in an issue first.

**Pull request closed without merging**
