### PR TITLE
Pass Boolean literals as becauseArguments

### PR DESCRIPTION
**Pull request by jnyrup**
## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by eNeRGy164** [comment]
Would this eliminate the possibility to have your own Boolean formatters?

**Review by dennisdoomen — APPROVED** [review]

**Comment by dennisdoomen** [comment]
> Would this eliminate the possibility to have your own Boolean formatters and influence the output?

Never thought about that. But I suspect it would require changes to a lot more places.

**Comment by jnyrup** [comment]
> > Would this eliminate the possibility to have your own Boolean formatters and influence the output?
> 
> Never thought about that. But I suspect it would require changes to a lot more places.

As far as I can tell it's only `BeTrue`, `BeFalse`, `NotBeTrue` and `NotBeFalse` that have constant Booleans.
So I could as well change this PR to inject the literals into `FailWith` to let any potential `BooleanFormatter` pick them up and format them.

**Comment by ITaluone** [comment]
> So I could as well change this PR to inject the literals into FailWith to let any potential BooleanFormatter pick them up and format them.

That would be cool :)

**Comment by IT-VBFK** [comment]
Should this also go the release notes? I think instead of the latest ("Capitalize `true` and `false`...")?

**Pull request merged**
