### PR TITLE
A few fixed qodana issues

### PR DESCRIPTION
**Pull request by ITaluone**
## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by jnyrup** [comment]
I don't see Qodana complaining about this. Where do you see this?

Secondly, should we just silence that analyzer instead?

**Comment by ITaluone** [comment]
> I don't see Qodana complaining about this. Where do you see this?

Pretty funny thing.. I accidentally double-clicked on the qodana.json inside Rider.. and suddenly the whole code was sprinkled with warnings 🙈 
I think these are issues from the baseline report.

**Review by dennisdoomen — APPROVED** [review]

**Comment by jnyrup** [comment]
> Secondly, should we just silence that analyzer instead?

If this cannot be automatically enforced on save across whatever IDE contributors are using, I don't think this consistency is worth pursuing.

Related [comment](https://github.com/fluentassertions/fluentassertions/pull/2144#discussion_r1151043759.) about trailing commas.

**Comment by ITaluone** [comment]
So... as I understand this correctly: The manual enforcement of such rules are not what we want?

**Comment by ITaluone** [comment]
Ignoring trailing comma complaints

I left the first commit remaining, since redundant parentheses are both unnecessary *and* confusing sometimes

**Review by jnyrup — APPROVED** [review]

**Pull request merged**
