### PR TITLE
add a target for .net 4.7 that doesn't include ValueTuple fix #757

### LINKED ISSUE #757: When installing the package in .net 4.7 it forces me to install ValueTuple

### PR DESCRIPTION
**Pull request by m3zercat**
I hope this is the right way to do this. I did build using the script and it changed all the assembly info files - not sure if I was supposed to include those in this pull request - can do if necessary

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Looks like what I was expecting although I suspected only an update to the .nuspec would be enough. Did you try to build the nuget package locally and then see if you could add it to a .NET 4.7 unit test project?

**Comment by m3zercat** [comment]
I'll admit I have no idea how to install a nuget package locally to a project. I did build the package and inspect it with Nuget Package Explorer to confirm that it looked ok.

**Comment by dennisdoomen** [comment]
Create a nuget package source that points to a local folder and then try to add that package to a .NET 4.7 project ;-)

**Comment by m3zercat** [comment]
Yep. done that. It installed just fine with no requirement for ValueTuple. Though I'm not sure - which bit of the fluent assertions code base required ValueTuple - I just want to confirm it works still. Though I'm sure it does.

**Comment by dennisdoomen** [comment]
It tries to support value tuples.

**Comment by m3zercat** [comment]
Awesome. Thanks

**Comment by dennisdoomen** [comment]
No, thank you!

**Pull request merged**
