### PR TITLE
Add Qodana

### PR DESCRIPTION
**Pull request by matkoch**
Setup:

- Create an organization, team, and project on https://qodana.cloud/ (enable _Make the organization public_)
- Copy token and add [here](https://github.com/fluentassertions/fluentassertions/settings/secrets/actions) as `QODANA_TOKEN`

### CODE REVIEW

**Review by dennisdoomen — APPROVED** [review]

**Comment by lg2de** [comment]
Where can we see the result of this analysis?
What is the benefit for FluentAssertions?
In the past [I asked for using SonarQube](https://github.com/fluentassertions/fluentassertions/pull/1320#issuecomment-621868573), which is maybe comparable a bit. Qodana seams to be accepted without any discussion.

**Comment by jnyrup** [comment]
Interesting stuff, let's give it a go and see if it's something for us.

@matkoch Have you seen that the pipeline fails to read `qodana.sarif.json`?

**Comment by matkoch** [comment]
@jnyrup yes I discussed it with Dennis already. It should work once merged, this is a special case/bug for Qodana because the PR itself introduces the baseline report. If it fails anyway, just revert and I will investigate once more, but dev team said it should be fine :)

**Review by jnyrup — APPROVED** [review]

**Comment by lg2de** [comment]
> It's working..

Unfortunately it is not visible to public. (Yes, I logged myself.)

**Comment by dennisdoomen** [comment]
@matkoch is there a way to give contributors access to the report?

**Pull request merged**
