### PR TITLE
DataSet Collections: ContainItemWithName

### PR DESCRIPTION
**Pull request by logiclrd**
This PR adds functionality on top of the `DataSet` assertions which was originally written for #1812 but which got moved out for its own independent pull request/evaluation. The changes apply to `DataTableCollection` and `DataColumnCollection`, which have elements that are logically named, and include unit tests and documentation.

## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [x] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [x] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [x] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

### CODE REVIEW

**Comment by jnyrup** [comment]
Also please move the API discussion to an issue.
Note how I edited #1896 with the proposed API.

**Comment by logiclrd** [comment]
API proposal discussion issue: #1897

**Comment by dennisdoomen** [comment]
As discussed in #1897, we decided not to make this API part of the library.

**Comment by logiclrd** [comment]
If I wanted to make my own extension library and make this a part of it, I would run into the problem that the code needs to identify the type `ReadOnlyNonGenericCollectionWrapper<TCollection, TItem>`, and that type is `internal`. What is the recommendation for this situation?

* Reflection? Slow and not type-safe.
* Make the type public? Leaky.
* `[InternalsVisibleTo]` in the main library?
* Other?

Thanks :-)

**Comment by dennisdoomen** [comment]
I can't think of any other way then just making that wrapper public. You can submit a PR for that if you want

**Comment by logiclrd** [comment]
Alright, will do. Thanks :-)

**Comment by logiclrd** [comment]
Oh, huh, the wrapper doesn't exist any more in the mainline. The code in this branch isn't compatible with 6.0 now that non-generic collection support got removed.

**Comment by logiclrd** [comment]
So, I never added unit tests explicitly asserting that basic collection functionality worked on `DataTableCollection`, `DataColumnCollection` and `DataRowCollection`. It "just worked" because these types implement `IEnumerable`. The lack of tests meant that when non-generic collection support was removed, it introduced an undetected regression in this area. I should have explicitly tested those types. Sigh. :-P

**Pull request closed without merging**
