### PR TITLE
Github -> GitHub

### PR DESCRIPTION
**Pull request by danielchalmers**

### CODE REVIEW

**Comment by jnyrup** [comment]
Can I ask you to include this commit as well?
https://github.com/jnyrup/fluentassertions/commit/dc15d9ff55b17a1aaf04c65b8b0cdab2ae264a2c

If anyone can teach me the skill of pushing a commit to a PR of a repo I'm admin of, I'll be grateful

**Comment by lg2de** [comment]
> If anyone can teach me the skill of pushing a commit to a PR of a repo I'm admin of, I'll be grateful

If @danielchalmers has enabled "Allow edits and access to secrets by maintainers" you should be able to push directly to Daniel's branch.

**Comment by danielchalmers** [comment]
Saved everyone the headache by making a new PR #2192 :)

**Comment by danielchalmers** [comment]
Oh I thought dc15d9ff55b17a1aaf04c65b8b0cdab2ae264a2c was on the master branch of the main project 🤦‍♂️

**Comment by jnyrup** [comment]
> > If anyone can teach me the skill of pushing a commit to a PR of a repo I'm admin of, I'll be grateful
> 
> If @danielchalmers has enabled "Allow edits and access to secrets by maintainers" you should be able to push directly to Daniel's branch.

It's the _how_ I'm struggling with.
I end up creating new branches on this repo or my fork instead of adding to _this_ branch 😞

**Comment by IT-VBFK** [comment]
> It's the how I'm struggling with.

Did you try to add the contributor's fork as remote, checking out his branch and committing/pushing changes?

**Comment by lg2de** [comment]
> It's the _how_ I'm struggling with.

I was firmly convinced that you know how to push on any existing branch.
In https://github.com/lg2de/SimpleAccounting/pull/231 I just pulled the contributor's branch and pushed my changes.

**Comment by jnyrup** [comment]
Apparently there are many ways to pull a branch that doesn't allow me pushing...
Thanks for triggering my stubbornness.

**Review by jnyrup — APPROVED** [review]

**Pull request merged**
