### PR TITLE
Add `[CustomAssertion]` attribute to extensibility docs

### PR DESCRIPTION
**Pull request by eranikid**
Continuing https://github.com/fluentassertions/fluentassertions/pull/2685 in a separate PR, due to my wrong branching choice

Description from original PR:

> There are (at least) two pages in the docs, that describe creating custom assertion methods - [Introduction](https://fluentassertions.com/introduction#subject-identification) and [Extensibility](https://fluentassertions.com/extensibility/#building-your-own-extensions)
> 
> `[CustomAssertion]` attribute is only mentioned in _Introduction_, along with a description of why including it is important, whereas in _Extensibility_ there is no mention of that attribute, and people googling https://www.google.com/search?q=fluent+assertions+how+to+create+custom+assertion will more likely land on _Extensibility_ rather than _Introduction_
> 
> This leads to confusion.
> 
> This PR adds a mention of `[CustomAssertion]` attribute to _Extensibility_ page

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by eranikid** [comment]
@dennisdoomen @ITaluone last PR was automatically closed by github when I reverted `develop` state in fork to match upstream by `push --force`. Even if it didn't, I'm not sure I could change head branch, so here is a new PR

**Comment by ITaluone** [comment]
That's correct now 🎉

**Comment by dennisdoomen** [comment]
Didn't you have more useful changes in the previous PR?

**Comment by eranikid** [comment]
@dennisdoomen No, that's all. Added `[CustomAssertion]` to the code and elaborated on why it's important

**Review by dennisdoomen — APPROVED** [review]

**Comment by dennisdoomen** [comment]
Oh wait. If you want to get this on the website, your PR needs to target `master`

**Comment by IT-VBFK** [comment]
Or wait for v7 to go on the website 😂

**Review by jnyrup — APPROVED** [review]

**Comment by eranikid** [comment]
Damn, I changed base branch, and now there is 353 commits and 80k changed lines. I probably need to branch of latest master in my branch and chery-pick the commits, hope the PR doesn't get closed again

**Comment by eranikid** [comment]
Ok, seems have worked, need another workflow approval and we should be good

**Pull request merged**
