### PR TITLE
Add Building and Testing categories

### PR DESCRIPTION
**Pull request by jnyrup**
Add two new categories for the autogenerated release notes template.

A bit unsure if the titles are descriptive enough 🤔

### CODE REVIEW

**Comment by IT-VBFK** [comment]
What about "building / composition"?

**Comment by jnyrup** [comment]
What does composition mean in this context?

To be more specific about my question.
Should it be more explicit that the two categories relates to building and testing FA and hence should not affect code consuming FA.

**Comment by IT-VBFK** [comment]
Ahh
Is it (from a consumer of FA) really necessary to know what changed on building and testing? I think not really first prio when reading the release notes.

You know what I mean?

**Comment by jnyrup** [comment]
Just to be clear, we have two sets of release notes.

1) https://github.com/fluentassertions/fluentassertions/blob/develop/docs/_pages/releases.md which should list everything affecting consumers.

2) https://github.com/fluentassertions/fluentassertions/releases which is an autogenerated list of every PR between two releases.

This PR only affects 2) and is about moving more PRs from the fallback category "Other" and into named categories.

**Comment by IT-VBFK** [comment]
Ok, then ignore all my noise here 🙈 

Sorry..

**Comment by jnyrup** [comment]
No need to be sorry, I appreciate your inputs and the extra set of eyes ❤️

**Comment by IT-VBFK** [comment]
Maybe add a description to the label and link to [here](https://github.com/fluentassertions/fluentassertions/labels) somehow?

**Comment by dennisdoomen** [comment]
🤔 What does "testing" mean? And why do we even care to mention them separately. In the end, it's just internal improvements, right?

**Comment by dennisdoomen** [comment]
I don't see much value in those, but if you do, knock yourself off ;-)

**Pull request closed without merging**
