### PR TITLE
Issue 1363

### PR DESCRIPTION
**Pull request by Serg046**
## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [x] If the contribution adds a feature or fixes a bug, please update [**the release notes**](https://github.com/fluentassertions/fluentassertions/tree/master/docs), which are published on the [website](https://fluentassertions.com/releases).
* [x] If the contribution changes the public API the changes needs to be included by running `AcceptApiChanges.ps1`/`AcceptApiChanges.sh`.
* [ ] If the contribution affects [the documentation](https://github.com/fluentassertions/fluentassertions/tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

Issue #1363

### CODE REVIEW

**Comment by Serg046** [comment]
We cannot just change DeclaringType to ReflectedType because of the following test (and Excluding version):
```csharp
[Fact]
public void When_including_a_property_that_is_hidden_in_a_derived_class_it_should_select_the_correct_one()
{
    // Arrange
    var b1 = new ClassThatHidesBaseClassProperty();
    var b2 = new ClassThatHidesBaseClassProperty();

    // Act / Assert
    b1.Should().BeEquivalentTo(b2, config => config.Including(b => b.Property));
}

private class ClassWithGuidProperty
{
    public string Property { get; set; } = Guid.NewGuid().ToString();
}

private class ClassThatHidesBaseClassProperty : ClassWithGuidProperty
{
    public new string[] Property { get; set; }
}
```
So the idea is the same as in the following existing method:
```csharp
public static PropertyInfo FindProperty(this Type type, string propertyName, Type preferredType)
{
    List<PropertyInfo> properties =
        type.GetProperties(PublicMembersFlag)
            .Where(pi => pi.Name == propertyName)
            .ToList();

    return properties.Count > 1
        ? properties.SingleOrDefault(p => p.PropertyType == preferredType)
        : properties.SingleOrDefault();
}
```
Below is what the fix does for the existing test (the first example of the comment)
1. We get the members - `string[] Property` and `string Property`.
2. We group the members with the same name.
3. When the member is unique, it is processed using the same way.
4. Otherwise, we look for the best match (**preferred** member) and process it, other members with that name are excluded from calculations. The best match is when the type of the property and CompileTimeType are the same.

**Comment by dennisdoomen** [comment]
Thanks for this fix. I'm going to have to postpone this for a week or two, because I'm finalizing some [significant refactoring](https://github.com/fluentassertions/fluentassertions/pull/1379) of the internal equivalency API. What would really help us if you would rebase your changes on that PR. I'm not expecting any major changes anymore.

**Comment by Serg046** [comment]
Sure, I will do it a bit later.
But anyway, not sure about the idea of the fix, it is maybe not the best solution here.

**Comment by dennisdoomen** [comment]
> Otherwise, we look for the best match (preferred member) and process it, other members with that name are excluded from calculations. The best match is when the type of the property and CompileTimeType are the same.

This will work for the top-level members of the graph, but as soon as FA dives into the graph, the `CompileTimeType` ends up being the run-time type of the nested members.

**Comment by Serg046** [comment]
Got it, I will take it into account when I will be moving the PR. Anyway, the same idea will work using ReflectedType which was added. I will just need to make it accessible somehow in the place where I need it. Thanks for the note.

**Pull request closed without merging**
