### PR TITLE
Add `WithOffset` helper extension method

### LINKED ISSUE #1192: Request for DateTime extension method to produce DateTimeOffset
### Description

I really like the fluent way of creating a DateTime. But I use DateTimeOffset all over my code to better handle timezones. There doesn't seem to be a fluent way to create a DateTimeOffset. 

The best I have come up with is:

`new DateTimeOffset(1.November(2019).As(10,0), TimeSpan.FromHours(-5));
`
It would be really nice if there was an extension that added the timezone offset to a DateTime that resulted in a DateTimeOffset. 

Something like:

`1.November(2019).As(10, 0).WithOffset(-5)`

Thanks

### PR DESCRIPTION
**Pull request by krajek**
Closes #1192.

Nothing special, simple wrapper, feels more fluent than existing `ToDateTimeOffset`.

### CODE REVIEW

**Comment by dennisdoomen** [comment]
We merged some big changes to `develop`. Please rebase. 

@jnyrup don't forget to review

**Comment by krajek** [comment]
Rebase done.

**Comment by jnyrup** [comment]
We dropped `net45`, `netstandard1.3` and `netstandard1.3` in #1227.
So they corresponding `approved.txt` files should not be re-added :)

**Comment by krajek** [comment]
@jnyrup thanks, done. I enjoy merging so much I wanted the process to last as long as possible 😂 .

**Pull request merged**
