### PR TITLE
Structure assertions with nested classes instead of regions (Part 5)

### PR DESCRIPTION
**Pull request by IT-VBFK**
## IMPORTANT 

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

### CODE REVIEW

**Review by jnyrup — APPROVED** [review]
I really wish github would support selecting diff algorithm.
Checking out the branch and running this made review a 2 minute task.
`git diff -wU0 --diff-algorithm=histogram develop`

**Comment by IT-VBFK** [comment]
As far as I have seen.. this PR was one of the last ones anyway :)

**Comment by IT-VBFK** [comment]
Ahhm.. small question: Should I move the tests from `Tests/Fluentasserion.Specs/Collections/CollectionAssertionSpecs.cs` to the appropriate files too?

**Review by dennisdoomen — APPROVED** [review]

**Comment by jnyrup** [comment]
> Ahhm.. small question: Should I move the tests from `Tests/Fluentasserion.Specs/Collections/CollectionAssertionSpecs.cs` to the appropriate files too?

Sure, go ahead.

**Comment by IT-VBFK** [comment]
Cool :)

**Pull request merged**
