### PR TITLE
Avoid treating `"\\r\\n"` as new line.

### PR DESCRIPTION
**Pull request by vbreuss**
As mentioned in #2566 treating the verbatim string `@"\r\n"` as a newline seems suspicius, as it is equivalent to `"\\r\\n"`.

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [x] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by vbreuss** [comment]
This code was added a long time ago in #84 ([see here](https://github.com/fluentassertions/fluentassertions/pull/84/files#diff-afb7da184f4c4a85d327db5f03007ae8ce9b5f2c7ae04a179b93c692232db626)).

**Review by dennisdoomen — APPROVED** [review]

**Comment by dennisdoomen** [comment]
I think the title is misleading. You're merely removing some code that doesn't do anything.

**Comment by vbreuss** [comment]
> I think the title is misleading. You're merely removing some code that doesn't do anything.

Not really. The following test failed previously, but now no longer:
```csharp
        [Fact]
        public void Does_not_treat_escaped_newlines_as_newlines()
        {
            // Arrange
            string actual = "te\r\nst";
            string expect = "te\\r\\nst";

            // Act / Assert
            actual.Should().NotMatchEquivalentOf(expect);
        }
```

image

Do you think it makes sense, to add this as a unit test?

**Comment by dennisdoomen** [comment]
> Not really. The following test failed previously, but now no longer

Ah, in that case, you're right and this is actually fixing a bug. Probably also needs a release notes entry then.

**Review by jnyrup — APPROVED** [review]

**Pull request merged**
