### PR TITLE
Add F# usage docs

### LINKED ISSUE #2299: Add Faqt link to docs
### Background and motivation

Continuing from https://github.com/fluentassertions/fluentassertions/issues/2225#issuecomment-1637767778 and subsequent comments.

Since F# support is [deemed out of scope](https://github.com/fluentassertions/fluentassertions/issues/2225#issuecomment-1636733116), I am wondering if you are open to linking to [Faqt](https://github.com/cmeeren/Faqt/). I imagine this could be done simply by adding a new page to the menu called "F# usage", around here:

image

On that page, we could have something like this:

> ### F# usage
> We encourage F# developers to try out [Faqt](https://github.com/cmeeren/Faqt/), an assertion library inspired by FluentAssertions and made specifically for F#.
> 
> FluentAssertions is made with C# in mind. While it can be used from F#, the syntax will be more verbose due to how F# overload resolution works. Improving F# usage issues is [deemed out of scope](https://github.com/fluentassertions/fluentassertions/issues/2225#issuecomment-1636733116) for FluentAssertions.

If you want me to submit a PR, please let me know approximately where I need to change things, and I'll jump on it.

### Alternative Concerns

_No response_

### Are you willing help with a pull-request?

Yes, please assign this issue to me.

### PR DESCRIPTION
**Pull request by cmeeren**
Fixes #2299

The spellcheck target of course fails on the word `Faqt`. Not sure what to do about that.

### CODE REVIEW

**Comment by ITaluone** [comment]
> The spellcheck target of course fails on the word Faqt. Not sure what to do about that.

Two possibilities:
1) Add `` around Faqt
2) Add Faqt to local cspell dictionary: cSpell.josn -> words

**Comment by cmeeren** [comment]
Done

**Comment by dennisdoomen** [comment]
In order for this to appear onthe website, you'll need to target `master`.

Also, did you run the site locally to see if everything works as expected?

**Comment by cmeeren** [comment]
> Also, did you run the site locally to see if everything works as expected?

No, didn't know I could. I just saw `run.bat` in `docs/`, but I don't have the dependencies for that (missing something called `bundle` which I've never heard of).

**Comment by cmeeren** [comment]
For what it's worth, I have viewed the new Markdown file in a markdown viewer, and that looks good at least.

**Comment by ITaluone** [comment]
I think, this is not what we want here?
image

**Comment by dennisdoomen** [comment]
> I think, this is not what we want here?

No, most definitely not. I guess you're new to git. But what you'll need is either to reset your branch to `master` and chery-pick your commit. Otherwise you would need to create a new PR.

**Comment by cmeeren** [comment]
Ah, I forgot to re-base on `master`. Will fix.

**Pull request closed without merging**
