### PR TITLE
WIP: Update global.json

### PR DESCRIPTION
**Pull request by matkoch**

### CODE REVIEW

**Comment by dennisdoomen** [comment]
The net effect of this PR is nothing?

**Comment by matkoch** [comment]
@dennisdoomen compiling with RTM release

**Comment by dennisdoomen** [comment]
But there are no changes.... https://github.com/fluentassertions/fluentassertions/pull/1163/files

**Comment by matkoch** [comment]
There were, but I'm currently troubleshooting.

Change was https://github.com/fluentassertions/fluentassertions/pull/1163/commits/861075c41e42ac9b79387547f72ead892b0b7644

**Comment by matkoch** [comment]
Fix will be available with NUKE 0.23.0. NuGet changed its behavior from `3.0.100-preview7-012821` to `3.0.100`.

**Comment by dennisdoomen** [comment]
Any need for this PR?

**Comment by jnyrup** [comment]
Updated global.json in #1195

**Pull request closed without merging**
