### PR TITLE
Add issue templates and api review process

### PR DESCRIPTION
**Pull request by jnyrup**
This adds an improved issue template much inspired/copied from:
* https://github.com/nuke-build/nuke/issues/new/choose
* https://github.com/dotnet/runtime/issues/new/choose

It's probably far from perfect and could benefit from a thorough revision, but here goes.

### CODE REVIEW

**Comment by eNeRGy164** [comment]
It would be nice if the description entered by the issuer would be above the standard boilerplate text.

This would make (push) notifications much better to read. Now every notification starts with
> **Before you file a bug, have you:**
>
>* Tried upgrading to newest version of Fluent Assertions,...

which doesn't add much value.

**Comment by jnyrup** [comment]
My initial attempt did even work as the description was above 200 characters...

Now it can be seen at https://github.com/jnyrup/fluentassertions/issues/new/choose

**Comment by jnyrup** [comment]
@eNeRGy164 I assume I solved your issue with, as https://github.com/jnyrup/fluentassertions/issues/4 was created via the template and doesn't include the "have you" part.

Let me know if I misunderstood your point.

**Comment by eNeRGy164** [comment]
Looks promising

**Review by dennisdoomen — APPROVED** [review]
Wow. What a great piece of work. I didn't even know about the YAML capabilities until I saw it being used in Nuke.

**Pull request merged**
