### PR TITLE
Fix NullableNumericAssertions<> methods throw NullReferenceException when subject is null

### PR DESCRIPTION
**Pull request by HajbokRobert**
…when subject is null

## IMPORTANT 

* [x] The [Pull Request](https://help.github.com/articles/using-pull-requests) is targeted at the `master` branch.
* [ ] The code complies with the [Coding Guidelines for C# 3.0, 4.0 and 5.0](http://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).
* [ ] If the contribution affects the documentation, please include your changes to [**documentation.md**](https://github.com/fluentassertions/fluentassertions/blob/master/docs/documentation.md) in this pull request so the documentation will appear on the [website](http://fluentassertions.com/documentation.html).

### CODE REVIEW

**Comment by dennisdoomen** [comment]
It has conflicts. After you've resolved them, I can merge the PR.

**Comment by jnyrup** [comment]
The conflicts are because it solved one of the problems, now solved by #788.

**Comment by dennisdoomen** [comment]
So we can close this one?

**Comment by jnyrup** [comment]
Yes.

**Pull request closed without merging**
