### PR TITLE
Fix the return type of TypeAssertions.HaveAccessModifier and NotHaveAccessModifier

### PR DESCRIPTION
**Pull request by adrianiftode**
#1154

* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by a new or existing set of unit tests which follow the Arrange-Act-Assert syntax such as is used [in this example](https://github.com/fluentassertions/fluentassertions/blob/daaf35b9b59b622c96d0c034e8972a020b2bee55/Tests/FluentAssertions.Shared.Specs/BasicEquivalencySpecs.cs#L33).

_The changes don't include a unit test, because I didn't see a common practice in the code base to test that the AndConstraint is closed with the correct type. The only test I've seen that checks for this particular situation is `When_using_StringCollectionAssertions_the_AndConstraint_should_have_the_correct_type`. I could add something similar._

* [x] If the contribution affects the documentation, please include your changes to [**documentation.md**](https://github.com/fluentassertions/fluentassertions/blob/master/docs/_pages/documentation.md) in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com).

There are no references in docs to these two assertions

### CODE REVIEW

**Comment by dennisdoomen** [comment]
I wondering whether we should treat this as a binary compatibility issue.

**Comment by adrianiftode** [comment]
It will be an issue, because the return type is changed and it will throw a `MethodNotFoundException`. The clients will need to recompile.

So for let's say if the current usage is something like:

`type.Should().HaveAccessModifier(CSharpAccessModifier.Internal).And.Should().BeAbstract();`

After this change the required step would be:

`type.Should().HaveAccessModifier(CSharpAccessModifier.Internal).And.BeAbstract();`

If the `AndConstraint` is not used, then the clients don't have to change the source code, just to recompile.

**Comment by dennisdoomen** [comment]
Yeah, so technically this would be a breaking change. But then again, how likely is this going to be a realistic problem. @jnyrup what do you think?

**Comment by dennisdoomen** [comment]
Can we continue with this one now that we're accepting potentially breaking changes again?

**Comment by jnyrup** [comment]
Let's continue with this!

@adrianiftode  Note that since #1217 any API change must be changed in the relevant [`approved.txt` files](https://github.com/fluentassertions/fluentassertions/tree/develop/Tests/Approval.Tests/ApprovedApi/FluentAssertions).
When you run the tests locally, `received.txt` files are generated in `Tests/Approval.Tests/ApprovedApi/FluentAssertions` with the API changes.
Copy these into `approved.txt` files to make the approval tests pass.

**Comment by adrianiftode** [comment]
@jnyrup I've run the tests as instructed.

When I first time run the tests my editor added an extra line at the end of the files and the tests failed. I wonder if these lines could be relaxed/ignored while asserting it.

**Comment by jnyrup** [comment]
Sorry, the flow has been improved since I suggested to "copy over the changes".
It should not be necessary to involve an IDE.
In the root folder of the project we now have `AcceptApiChanges.{sh,ps1}` to do the changes.
Would that avoid the problems you had?

**Comment by adrianiftode** [comment]
I just tried it and looks fine.

**Comment by jnyrup** [comment]
While I remember it...
Could I ask you to add a line to `docs/_pages/releases.md` under "Breaking Changes" with the changes done?

**Comment by jnyrup** [comment]
@adrianiftode Thanks again for reporting *and* contributing a fix for this issue.

**Comment by adrianiftode** [comment]
It's been a pleasure, thanks for guidance

vin., 21 feb. 2020, 16:57 Jonas Nyrup <notifications@github.com> a scris:

**Pull request merged**
