### PR TITLE
Markdown linting

### PR DESCRIPTION
**Pull request by eNeRGy164**
Every time I edited the release notes, Visual Studio Code was showing me a lot of markdown linting warnings.
This PR fixes these warnings.

This improves readability of the markdown files and applies some constructs more consistently.

I addressed:

* [MD003](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md003---heading-style)
* [MD009](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md009---trailing-spaces)
* [MD012](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md012---multiple-consecutive-blank-lines)
* [MD022](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md022---headings-should-be-surrounded-by-blank-lines)
* [MD026](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md026---trailing-punctuation-in-heading)
* [MD031](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md031---fenced-code-blocks-should-be-surrounded-by-blank-lines)
* [MD036](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md036---emphasis-used-instead-of-a-heading)
* [MD038](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md038---spaces-inside-code-span-elements)
* [MD040](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md040---fenced-code-blocks-should-have-a-language-specified)
* [MD047](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md047---files-should-end-with-a-single-newline-character)

I added a CSS rule to keep the layout reflecting the original page.
I also added an additional way to easily set up a Ruby development environment on Windows.

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Can you add a screenshot?

**Comment by eNeRGy164** [comment]
Of the website?
image

**Review by dennisdoomen — APPROVED** [review]

**Review by jnyrup — APPROVED** [review]
Out of curiosity, is [MD040](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md040---fenced-code-blocks-should-have-a-language-specified)  triggered by `cs` or `c#`?
I mostly use `cs` instead of `csharp` and a quick search seems to indicate that vs-code supports [`cs|csharp|c#`](https://github.com/microsoft/vscode/pull/12279/files)

**Comment by eNeRGy164** [comment]
> Out of curiosity, is [MD040](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md040---fenced-code-blocks-should-have-a-language-specified) triggered by `cs` or `c#`?
> I mostly use `cs` instead of `csharp` and a quick search seems to indicate that vs-code supports [`cs|csharp|c#`](https://github.com/microsoft/vscode/pull/12279/files)

No MD040 is only triggered if it isn't present. So add something if not present, but just aligned the value for other occurences.

**Pull request merged**
