### PR TITLE
Update documentation: Add missing tip for `ContainItemsAssignableTo<T>()`

### LINKED ISSUE #1841: [Docs] ContainItemsAssignableTo
With the fixes for #1618 the docs need updating.

https://fluentassertions.com/tips/#collections

|MSTest|FluentAssertions
|-|-|
|`CollectionAssert.AllItemsAreInstancesOfType(actual, typeof(T));`|`actual.Should().ContainItemsAssignableTo<T>();`|
|CollectionAssert.AllItemsAreInstancesOfType failed. Element at index 0 is not of expected type. Expected type:<UnitTests2.MyIdenticalClass>. Actual type:<UnitTests2.MyClass>.|Expected collection to contain only items of type UnitTests2.MyIdenticalClass, but item SomeProperty: 1, OtherProperty: item at index 0 is of type UnitTests2.MyClass.|

### PR DESCRIPTION
**Pull request by IT-VBFK**
This refs and closes #1841

## IMPORTANT 

* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).

### CODE REVIEW

**Review by dennisdoomen — APPROVED** [review]

**Review by jnyrup — APPROVED** [review]

**Comment by jnyrup** [comment]
Wait a minute...
#1841 is not about a missing tip, but the existing tip being wrong.
The change is here is to replace `ContainItemsAssignableTo` with `AllBeAssignableTo` adjust the failure message.

**Review by jnyrup — CHANGES_REQUESTED** [review]
Wait a minute...
#1841 is not about a missing tip, but the existing tip being wrong.
The change is here is to replace `ContainItemsAssignableTo` with `AllBeAssignableTo` adjust the failure message.

**Comment by IT-VBFK** [comment]
Ahh.. got it.. this is not a "tip" in first place, but a documentation about migrating from mstest

**Comment by jnyrup** [comment]
I'm sorry, but this is still not the right change.

When I initially wrote `collectionAssert.yml` `CollectionAssert.AllItemsAreInstancesOfType` and `ContainItemsAssignableTo` would do the same, but since #1765 was merged they no longer.
Now `AllBeAssignableTo` is the equivalent method in Fluent Assertions to use, when migrating from MSTest.

So the necessary parts to update are:
https://github.com/fluentassertions/fluentassertions/blob/654827f9357b93a7d6431a6ff8cff248d8b4483b/docs/_data/mstest-migration/collectionAssert.yml#L125
to use `AllBeAssignableTo<T>()`
and adjust the failure message on https://github.com/fluentassertions/fluentassertions/blob/654827f9357b93a7d6431a6ff8cff248d8b4483b/docs/_data/mstest-migration/collectionAssert.yml#L131 to what `AllBeAssignableTo<T>()` outputs.

**Comment by IT-VBFK** [comment]
Oh.. I see :)

sorry for stealing your time with reviews here

**Comment by IT-VBFK** [comment]
so.. hopefully this was the correct change..

**Review by jnyrup — APPROVED** [review]

**Pull request merged**
