### PR TITLE
Merge 'master' into 'develop'

### PR DESCRIPTION
**Pull request by adamvoss**
Done primarily so the website/documentation exists on the develop branch so changes related to FA 5.0 can be included.

### CODE REVIEW

**Comment by dennisdoomen** [comment]
Looks like some code got merged in as well

**Comment by adamvoss** [comment]
Is **master** -> **develop** not a merge path?  I assumed it was since **master** is indicated as where bugs should be fixed.

If it is not, I could merge be4714cb940be55add2a58c1c56f5ad0025e8940 and cherry-pick latter website-only changes, but I don't typically like doing that to history.  Perhaps it would be better to close this and wait until **develop** becomes **master**.  I was mainly just looking to make it so **develop** would be set with the new logo per https://github.com/fluentassertions/fluentassertions/issues/533#issuecomment-305571836.

**Comment by dennisdoomen** [comment]
It is, so I don't get why it doesn't compile.

**Comment by adamvoss** [comment]
I didn't at first either.  Turns out the reason was above all the red text: some added unit tests needed to be adapted for the XUnit switch.

**Pull request merged**
