### PR TITLE
Add `[StringSyntax("CompositeFormat")]` to all `because` parameters

### PR DESCRIPTION
**Pull request by psychotoad**
Implements #2630 

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Review by dennisdoomen — APPROVED** [review]
For some reason the Qodana scan failed.

**Comment by psychotoad** [comment]
I don't really understand what is wrong or what I am supposed to do.

**Comment by dennisdoomen** [comment]
> I don't really understand what is wrong or what I am supposed to do.

It doesn't seem to be related to your changes. We're investigating it.

**Comment by ITaluone** [comment]
@psychotoad try rebase onto current develop and force push

**Comment by psychotoad** [comment]
Qodana now shows "String formatting method problems" in the tests. How do I disable these checks in the tests?

**Comment by ITaluone** [comment]
You could add

```yml
- name: FormatStringProblem
    paths:
      - Tests
```

to qodana.yml (root directory) if you want to disable it completely for the given paths

OR

add `// ReSharper disable once FormatStringProblem` before every occurrence

**Comment by ITaluone** [comment]
Huh.. thats weird..

can you try the other method?

**Comment by psychotoad** [comment]
Wait, now only 4 out of 5 warnings got ignored?

**Comment by dennisdoomen** [comment]
> add `// ReSharper disable once FormatStringProblem` before every occurrence

This should work.

**Comment by psychotoad** [comment]
> > add `// ReSharper disable once FormatStringProblem` before every occurrence
> 
> This should work.

For some reason it did not in one place. I solved it with with disable + restore.

**Comment by IT-VBFK** [comment]
Have you noticed the compile error in last pipeline run?

**Comment by psychotoad** [comment]
> Have you noticed the compile error in last pipeline run?
> 
> https://github.com/fluentassertions/fluentassertions/actions/runs/9318831327/job/25663184462

Thanks for notifying me.

**Review by jnyrup — APPROVED** [review]

**Pull request merged**
