### PR TITLE
Checkout the merge commit for Qodana to generate correct results

### PR DESCRIPTION
**Pull request by ITaluone**
## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by ITaluone** [comment]
Using `fetch_depth=0` is also unnecessary for Qodana, right?

**Comment by dennisdoomen** [comment]
> Using `fetch_depth=0` is also unnecessary for Qodana, right?

According to the [docs](https://www.jetbrains.com/help/qodana/github.html#Usage), we do...

**Comment by IT-VBFK** [comment]
Interestingly it uses `fetch_depth=0` in every case (see the build logs), even if it is set to 1

**Comment by jnyrup** [comment]
> Interestingly it uses `fetch_depth=0` in every case (see the build logs), even if it is set to 1

I don't see it, can you point at it?


> > Using `fetch_depth=0` is also unnecessary for Qodana, right?
> 
> According to the [docs](https://www.jetbrains.com/help/qodana/github.html#Usage), we do...

As I read it `fetch-depth=0` is only strictly needed for pr-mode, so we could use `fetch-depth=1` for non-pr mode.
But I have no idea of what difference it would make, but I estimate it won't be that much since the checkout step with `fetch-depth=0` takes 11s 🤷

**Comment by dennisdoomen** [comment]
> so we could use `fetch-depth=1` for non-pr mode.

I'm pretty sure it'll break GitVersion, since it needs the completely history.

**Comment by IT-VBFK** [comment]
> I'm pretty sure it'll break GitVersion, since it needs the completely history.

As I understand this: The Qodana pipeline is a different one than the usual `build`. So this shouldn't matter, I believe.

**Review by dennisdoomen — APPROVED** [review]

**Review by jnyrup — APPROVED** [review]

**Comment by IT-VBFK** [comment]
>  I don't see it, can you point at it?

Take this as an example:
https://github.com/fluentassertions/fluentassertions/actions/runs/6347891564/job/17243569462

This was a Qodana scan for this commit: https://github.com/fluentassertions/fluentassertions/commit/12df7d0b7672dbecbc94b3a3f95889073487a601
(with `fetch_depth=1`)

and the output shows:
image

**Pull request merged**
