### PR TITLE
Fix Possible 'System.NullReferenceException' warning from Rider and Qodana

### PR DESCRIPTION
**Pull request by lg2de**

### CODE REVIEW

**Review by dennisdoomen — APPROVED** [review]
I still have doubts about all those `!`, but we'll see.

**Review by Corniel — APPROVED** [review]
LGTM.

**Comment by IT-VBFK** [comment]
Do you mind adding those 7 possible NRE too?

image

**Comment by lg2de** [comment]
@IT-VBFK I'll take a look tonight.

**Comment by lg2de** [comment]
I focused on the issues which are fixable with `!` because the subject is already checked.
For easier review I do not handler other issues here.

**Review by jnyrup — APPROVED** [review]
I looked through all the changes and agree that we have more knowledge than the compiler here.

**Pull request merged**
