### PR TITLE
Optimize `TypeMemberReflector`

### PR DESCRIPTION
**Pull request by jnyrup**
Picking some low-hanging fruits in `TypeMemberReflector` to speed it up a bit.

The `_Old` suffix is the version of `TypeMemberReflector` in `develop`.
The "Ratio" column is manually calculated as `new / old`

|                                    Method |     Mean | Ratio |     Error |    StdDev |   Gen0 | Allocated | Ratio |
|------------------------------------------ |---------:|------:|----------:|----------:|-------:|----------:|------:|
|                                   Publicc | 2.759 us |  0.55 | 0.0548 us | 0.0631 us | 0.5646 |   3.46 KB |  0.60 |
|                               Publicc_Old | 5.006 us |       | 0.0433 us | 0.0384 us | 0.9384 |   5.77 KB |       |
|                           Public_Internal | 4.190 us |  0.60 | 0.0386 us | 0.0342 us | 0.8240 |   5.06 KB |  0.70 |
|                       Public_Internal_Old | 6.947 us |       | 0.0212 us | 0.0177 us | 1.1673 |   7.18 KB |       |
|     Public_Internal_ExplicitlyImplemented | 6.302 us |  0.90 | 0.0206 us | 0.0182 us | 1.0071 |   6.20 KB |  0.84 |
| Public_Internal_ExplicitlyImplemented_Old | 7.017 us |       | 0.0212 us | 0.0198 us | 1.1902 |   7.34 KB |       |

## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [ ] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

### CODE REVIEW

**Comment by jnyrup** [comment]
The file still has 100% line and branch coverage.
The reduction is because we now do the same in less code.

Duplicate check of `!field.IsPrivate`
image

We null-Guarded `GetMethod` in `IsExplicitImplementation` and later removing members without a getter.
image

**Review by dennisdoomen — APPROVED** [review]
What about the Qodana issue?

**Comment by jnyrup** [comment]
> What about the Qodana issue?

Hadn't noticed that.

Qodana cannot see that `HasGetter` filters out properties without a `GetMethod`.

So either the code must be restructured to make that visible to Qodana, or we add `!` in `IsExplicitImplementation`

**Comment by dennisdoomen** [comment]
> So either the code must be restructured to make that visible to Qodana, or we add `!` in `IsExplicitImplementation`

That's what my pragmatic mind would do ;-)

**Pull request merged**
