### PR TITLE
Fix build breaking on non PR branches

### PR DESCRIPTION
**Pull request by IT-VBFK**
## IMPORTANT 

* [ ] If the PR touches the public API, the changes have been approved in a separate issue with the "api-approved" label.
* [x] The code complies with the [Coding Guidelines for C#](https://www.csharpcodingguidelines.com/).
* [ ] The changes are covered by unit tests which follow the Arrange-Act-Assert syntax and the naming conventions such as is used [in these tests](../tree/develop/Tests/FluentAssertions.Equivalency.Specs/MemberMatchingSpecs.cs#L51-L430).
* [ ] If the PR adds a feature or fixes a bug, please update [the release notes](../tree/develop/docs/_pages/releases.md) with a functional description that explains what the change means to consumers of this library, which are published on the [website](https://fluentassertions.com/releases).
* [ ] If the PR changes the public API the changes needs to be included by running [AcceptApiChanges.ps1](../tree/develop/AcceptApiChanges.ps1) or [AcceptApiChanges.sh](../tree/develop/AcceptApiChanges.sh).
* [ ] If the PR affects [the documentation](../tree/develop/docs/_pages), please include your changes in this pull request so the documentation will appear on the [website](https://www.fluentassertions.com/introduction).
    * [ ] Please also run `./build.sh --target spellcheck` or `.\build.ps1 --target spellcheck` before pushing and check the good outcome

My fault.. ~~over-optimized code..~~ should be fixed now 

`PullRequestBase` is empty and not `null`/`default`

### CODE REVIEW

**Comment by IT-VBFK** [comment]
Main reason for this failure is, that apparently `github.event.pull_request.base.ref` and therefore `PullRequestBase` is not `default`, because on my local dev device it works.

Do anybody know what default value `github.event.pull_request.base.ref` has, when merging a PR?

**Comment by dennisdoomen** [comment]
> Do anybody know what default value github.event.pull_request.base.ref has, when merging a PR?

I guess it's an empty string.

**Comment by IT-VBFK** [comment]
Ok.. then this should be fixed now.

**Comment by IT-VBFK** [comment]
Thinking out loud.. Maybe it is possible to have some sort of unit tests for the build project to avoid such issues in future..

**Comment by dennisdoomen** [comment]
> Thinking out loud.. Maybe it is possible to have some sort of unit tests for the build project to avoid such issues in future..

No worries. That's why we have builds in the first place.

**Comment by IT-VBFK** [comment]
Looks good 🙃

**Pull request merged**
